### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 2)

### ISSUE THREAD

**Issue by Ianmcmill** [mlberkeley/Creative-Adversarial-Networks#26]
I am trying to run this on windows 10.
Python 3.6 64bit
tensorflow-gpu 1.4.0
With wikiart in ./data/wikiart
When runnning:
`python main.py --epoch 25 --learning_rate .0001 --beta 0.5 --batch_size 16 --sample_size 16 --input_height 32 --output_height 32 --lambda_val 1.0 --smoothing 1.0 --use_resize True --dataset wikiart --input_fname_pattern */*.jpg --crop False --visualize True --can True --train True`
I get:
```
python main.py --epoch 25 --learning_rate .0001 --beta 0.5 --batch_size 16 --sample_size 16 --input_height 32 --output_height 32 --lambda_val 1.0 --smoothing 1.0 --use_resize True --dataset wikiart --input_fname_pattern */*.jpg --crop False --visualize True --can True --train True
Before processing flags
{'allow_gpu_growth': False,
 'batch_size': 16,
 'beta1': 0.5,
 'can': True,
 'checkpoint_dir': None,
 'crop': False,
 'dataset': 'wikiart',
 'epoch': 25,
 'input_fname_pattern': '*/*.jpg',
 'input_height': 32,
 'input_width': None,
 'lambda_val': 1.0,
 'learning_rate': 0.0001,
 'load_dir': None,
 'log_dir': 'logs',
 'output_height': 32,
 'output_width': None,
 'replay': True,
 's3_bucket': None,
 'sample_dir': None,
 'sample_itr': 500,
 'sample_size': 16,
 'save_itr': 500,
 'smoothing': 1.0,
 'style_net_checkpoint': None,
 'train': True,
 'train_size': inf,
 'use_default_checkpoint': False,
 'use_resize': True,
 'use_s3': False,
 'visualize': True,
 'wgan': False}
After processing flags
{'allow_gpu_growth': False,
 'batch_size': 16,
 'beta1': 0.5,
 'can': True,
 'checkpoint_dir': 'logs\\dataset=wikiart,isCan=True,lr=0.0001,imsize=32,hasStyleNet=False,batch_size=16\\000\\checkpoint',
 'crop': False,
 'dataset': 'wikiart',
 'epoch': 25,
 'input_fname_pattern': '*/*.jpg',
 'input_height': 32,
 'input_width': 32,
 'lambda_val': 1.0,
 'learning_rate': 0.0001,
 'load_dir': None,
 'log_dir': 'logs\\dataset=wikiart,isCan=True,lr=0.0001,imsize=32,hasStyleNet=False,batch_size=16\\000',
 'output_height': 32,
 'output_width': 32,
 'replay': True,
 's3_bucket': None,
 'sample_dir': 'logs\\dataset=wikiart,isCan=True,lr=0.0001,imsize=32,hasStyleNet=False,batch_size=16\\000\\samples',
 'sample_itr': 500,
 'sample_size': 16,
 'save_itr': 500,
 'smoothing': 1.0,
 'style_net_checkpoint': None,
 'train': True,
 'train_size': inf,
 'use_default_checkpoint': True,
 'use_resize': True,
 'use_s3': False,
 'visualize': True,
 'wgan': False}
Abstract_Expressionism
Action_painting
Analytical_Cubism
Art_Nouveau_Modern
Baroque
Color_Field_Painting
Contemporary_Realism
Cubism
Early_Renaissance
Expressionism
Fauvism
High_Renaissance
Impressionism
Mannerism_Late_Renaissance
Minimalism
Naive_Art_Primitivism
New_Realism
Northern_Renaissance
Pointillism
Pop_Art
Post_Impressionism
Realism
Rococo
Romanticism
Symbolism
Synthetic_Cubism
Ukiyo_e
2018-10-28 14:36:09.248951: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
2018-10-28 14:36:09.514326: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties:
name: GeForce GTX 980 major: 5 minor: 2 memoryClockRate(GHz): 1.291
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.29GiB
2018-10-28 14:36:09.527564: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:01:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "main.py", line 156, in <module>
    tf.app.run()
  File "C:\Users\castle\Envs\can\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 147, in main
    dcgan.train(FLAGS)
  File "D:\fakes\CAN_origin\model.py", line 223, in train
    sample_labels = self.get_y(sample_files)
  File "D:\fakes\CAN_origin\model.py", line 453, in get_y
    _, _, _, lab_str, _ = sample.split('/', 4)
ValueError: not enough values to unpack (expected 5, got 2)
```

**Comment by galoisgroupcn** [comment]
@Ianmcmill Hi lanmcmill, have you tried it on Linux?

**Comment by galoisgroupcn** [comment]
@Ianmcmill Hi lanmcmill! Are you still working on this project? I'm working on it on Google Colab. Would you like to work together?

Best,

Amber Ji
